#- name: NodeJS App Setup
#  include_role:
#    name: common
#    tasks_from: nodejs
- name: Sample command
  shell: "echo {{ lookup('amazon.aws.aws_secret', 'dev/roboshop/secrets', region='us-east-1')}} >/tmp/out"
  register: out

- name: lookup secretsmanager secret in the current region
  debug: msg="{{ out.stdout }}"
  