- name: Configure YUM repos.
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Project Application User

- name: Download and Extract Frontend
  include_role:
    name: common
    tasks_from: download

- name: Cleanup Old Content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy App Content
  become_user: roboshop
  ansible.builtin.copy:
    dest: /home/roboshop/catalogue/
    src: /tmp/catalogue-main/
    remote_src: yes

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Copy SystemD File
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Catalogue Service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes
