#- name: NodeJS App Setup
#  include_role:
#    name: common
#    tasks_from: nodejs

- name: lookup secretsmanager secret in the current region
  debug: msg="{{ lookup('amazon.aws.aws_secret', 'dev/roboshop/secrets', region=us-east-1, bypath=true) }}"
  