- name: Fetch Secrets
  shell: "echo {{lookup('amazon.aws.aws_secret', 'dev/roboshop/secrets', region='us-east-1') | to_json}} | jq"
  register: out

- name: Set Secrets
  set_fact:
    secrets: "{{ out.stdout | from_json }}"
