- name: Add Application User
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Project Application User
  register: APP_USER_REGISTER

### As per standard process we download the software from a release rather than
### from git repo. Hence we are commenting an

#- name: Download and Extract {{COMPONENT}}
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes

- name: Cleanup Old Content
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: absent

- name: Copy App Content
  become_user: "{{APP_USER}}"
  ansible.builtin.copy:
    dest: "{{APP_LOCATION}}"
    src: /tmp/{{COMPONENT}}-main/
    remote_src: yes
