- name: Install Python3
  ansible.buitin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Setup App USer, Download and Extract {{COMPONENT}} Content
  include_role:
    name: common
    tasks_from: download

- name: Install Python Dependencies
  pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Setup SyetemD
  include_role:
    name: common
    tasks_from: systemd
